name: 'docker'

on:
  push:
    branches:
    - adding-github
    - main

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: 'Docker CI/CD'
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER_NAME: eks-vic

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v1


    # Check AWS credentials 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        # role-to-assume: arn:aws:iam::533267153411:role/role_for_tf
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    
    # Login to the ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    # Docker Build, Tag and Push
    - name: Build, tag, and push image to Amazon ECR
      id: docker-push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: httpbin
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    - name: Update Kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
        kubectl get svc -n vic-ns
        helm list -n vic-ns


    - name: Update Helm With My New Image
      id: helm-upgrade
      env:
        ECR_REGISTRY: ${{ steps.docker-push.outputs.registry }}
        ECR_REPOSITORY: httpbin
        HELM_NAME: httpbin
        HELM_CHART_NAME: httpbingo/
        IMAGE_TAG: latest
      run: |
        echo "the URI: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        helm upgrade $HELM_NAME $HELM_CHART_NAME --set ingress.hosts[0].host="k8s-vicns-httpbin-e1483db053-318127809.us-east-1.elb.amazonaws.com",image.tag=$IMAGE_TAG --values httpbin-values.yaml -n vic-ns
      

    - name: Check Helm In EKS
      run: |
        kubectl get svc -n vic-ns
        helm list -n vic-ns
